### ISSUE TITLE
ValueError: zero-dimensional arrays cannot be concatenated

### ISSUE THREAD

**Issue by chj1933** [seathiefwang/MGN-pytorch#2]
when I run sh demo.sh 
[INFO] Making loss...
1.000 * CrossEntropy
1.000 * Triplet
[INFO] Epoch: 1	Learning rate: 2.00e-04

[INFO] Test:
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    trainer.test()
  File "/media/data2/chenghj/RE-ID/MGN-pytorch-master/trainer.py", line 74, in test
    dist = re_ranking(q_g_dist, q_q_dist, g_g_dist)
  File "/media/data2/chenghj/RE-ID/MGN-pytorch-master/utils/re_ranking.py", line 44, in re_ranking
    [np.concatenate([q_q_dist, q_g_dist], axis=1),
ValueError: zero-dimensional arrays cannot be concatenated

please tell me how to correct it . thanks!

**Comment by seathiefwang** [comment]
can you show me your demo.sh file? it is ok when i run it.

**Comment by chj1933** [comment]
@seathiefwang ，if I want to use my own dataset , how to train it?

**Comment by seathiefwang** [comment]
You need to write code to parse your data.

**Comment by chj1933** [comment]
@seathiefwang , If i use my own dataset ,  It's appropriate what parameters should I usually  adjust?

**Comment by seathiefwang** [comment]
`--datadir` you need modify this parameter.

**Comment by chj1933** [comment]
@seathiefwang  ，thanks! It works when I use my own dataset , but the mAP and rank1 are not very high , if I want to improve the mAP and rank1,  It's appropriate what parameters should I usually adjust?

**Comment by seathiefwang** [comment]
#1

**Comment by chj1933** [comment]
@seathiefwang ，please tell me how are your training parameters set？I always lower 1% than your,  it can't achieve rank1 95.8% and mAP 93.5%

**Comment by seathiefwang** [comment]
You can change parameters and  try more times.

**Comment by chj1933** [comment]
@seathiefwang ，你好，若果我用自己的数据训练，我在解析自己的数据时候除了修改（market1501.py）把ID信息和摄像头信息导入,还要修改哪里嘛？不然会在dist = cdist(qf,gf)显示XA must be a 2-dimensional array
